!!! init_tp by default: 
!!! Using z3
Starting z3... 

Last Proving Location: 1 File "slk/bug-6a-covariant-latch.slk",Line:4,Col:10

ERROR: at slk/bug-6a-covariant-latch.slk_6:10_6:25
Message: compute_view_fw_bw: data not found: LatchOut

Entail 1: Fail.(must) cause:matching of ho_args failed ( 0<n |-  3<n. LOCS:[10;9] (may-bug))

Residue:
 <1>emp&{FLOW,(1,26)=__flow#E}[]


Entail 2: Valid. 

Residue:
 <1>emp&6<n&{FLOW,(4,5)=__norm#E}[]
[[ COND ==>  Match(c,c) ==> ]]



Entail 3: Valid. 

Residue:
 <1>emp&3<n&{FLOW,(4,5)=__norm#E}[]
[[ COND ==>  Match(c,c) ==> ]]



Entail 4: Fail.(must) cause:matching of ho_args failed ( 3<n |-  6<n. LOCS:[27;28] (may-bug))

Residue:
 <1>emp&{FLOW,(1,26)=__flow#E}[]


